SET IDENTITY_INSERT [dbo].[Producer] ON
INSERT INTO [dbo].[Producer] ([ProducerID], [Producer_name]) VALUES (1, N'Bábolna Bio')
INSERT INTO [dbo].[Producer] ([ProducerID], [Producer_name]) VALUES (1, N'Bábolna Bio')
INSERT INTO [dbo].[Producer] ([ProducerID], [Producer_name]) VALUES (2, N'Chemitat')
INSERT INTO [dbo].[Producer] ([ProducerID], [Producer_name]) VALUES (3, N'Colgate-Palmolive')
INSERT INTO [dbo].[Producer] ([ProducerID], [Producer_name]) VALUES (4, N'Cuxson Gerrard')
INSERT INTO [dbo].[Producer] ([ProducerID], [Producer_name]) VALUES (5, N'Ecover')
INSERT INTO [dbo].[Producer] ([ProducerID], [Producer_name]) VALUES (6, N'EVM')
INSERT INTO [dbo].[Producer] ([ProducerID], [Producer_name]) VALUES (7, N'FHCS')
INSERT INTO [dbo].[Producer] ([ProducerID], [Producer_name]) VALUES (8, N'Fourth Kft.')
INSERT INTO [dbo].[Producer] ([ProducerID], [Producer_name]) VALUES (9, N'Greenbiotic')
INSERT INTO [dbo].[Producer] ([ProducerID], [Producer_name]) VALUES (10, N'Henkel')
INSERT INTO [dbo].[Producer] ([ProducerID], [Producer_name]) VALUES (11, N'Hurricane')
INSERT INTO [dbo].[Producer] ([ProducerID], [Producer_name]) VALUES (12, N'Manifest-Impex Kft.')
INSERT INTO [dbo].[Producer] ([ProducerID], [Producer_name]) VALUES (13, N'Marca-Delta')
INSERT INTO [dbo].[Producer] ([ProducerID], [Producer_name]) VALUES (14, N'Orion')
INSERT INTO [dbo].[Producer] ([ProducerID], [Producer_name]) VALUES (15, N'Other')
INSERT INTO [dbo].[Producer] ([ProducerID], [Producer_name]) VALUES (16, N'P&G')
INSERT INTO [dbo].[Producer] ([ProducerID], [Producer_name]) VALUES (17, N'Private label')
INSERT INTO [dbo].[Producer] ([ProducerID], [Producer_name]) VALUES (18, N'Reckitt-Benckiser')
INSERT INTO [dbo].[Producer] ([ProducerID], [Producer_name]) VALUES (19, N'Renew Technologies')
INSERT INTO [dbo].[Producer] ([ProducerID], [Producer_name]) VALUES (20, N'Sara Lee')
INSERT INTO [dbo].[Producer] ([ProducerID], [Producer_name]) VALUES (21, N'SC Johnson')
INSERT INTO [dbo].[Producer] ([ProducerID], [Producer_name]) VALUES (22, N'Spotless')
INSERT INTO [dbo].[Producer] ([ProducerID], [Producer_name]) VALUES (23, N'Unilever')
INSERT INTO [dbo].[Producer] ([ProducerID], [Producer_name]) VALUES (24, N'Volmix')
INSERT INTO [dbo].[Producer] ([ProducerID], [Producer_name]) VALUES (25, N'Well Done')
INSERT INTO [dbo].[Producer] ([ProducerID], [Producer_name]) VALUES (26, N'Werner Mertz')
INSERT INTO [dbo].[Producer] ([ProducerID], [Producer_name]) VALUES (27, N'Yak')
SET IDENTITY_INSERT [dbo].[Producer] OFF
