SET IDENTITY_INSERT [dbo].[Brand] ON
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (1, N'Ajax')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (2, N'Alex')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (3, N'Anandam')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (4, N'Ariel')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (5, N'Autan')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (6, N'BIOSTOP')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (7, N'Bref')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (8, N'Chemitat')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (9, N'Chemotox')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (10, N'Cif')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (11, N'Cillit')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (12, N'Cillit Bang')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (13, N'Cleanne')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (14, N'Clin')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (15, N'Coccolino')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (16, N'Cycle')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (17, N'Dettol')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (18, N'Domestos')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (19, N'Domotox')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (20, N'Dr. Beckmann')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (21, N'Dr. M')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (22, N'Dreft')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (23, N'Dual Power')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (24, N'Duck')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (25, N'Ecover')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (26, N'Erdal')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (27, N'Finish')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (28, N'Flóraszept')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (29, N'Frosch')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (30, N'Galaktivbio')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (31, N'Green Emotion')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (32, N'Greenbiotic')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (33, N'Harpic')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (34, N'Harpic-Cillit')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (35, N'Herbow')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (36, N'Jar')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (37, N'Kiwi')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (38, N'Lanza')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (39, N'LArbre Vert')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (40, N'Lenor')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (41, N'MaxSan')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (42, N'Mr. Muscle')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (43, N'Mr.Proper')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (44, N'Naturland')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (45, N'No.1')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (46, N'Off')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (47, N'Opti')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (48, N'Orion')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (49, N'Persil')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (50, N'Perwoll')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (51, N'Pronto')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (52, N'PROTECT')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (53, N'Punch')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (54, N'Pur')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (55, N'Raid')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (56, N'Sansin')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (57, N'Sanytol')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (58, N'Seventh')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (59, N'Silan')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (60, N'Sitsef')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (61, N'Sodasan')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (62, N'Softenerix')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (63, N'Somat')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (64, N'S-quitofree')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (65, N'Surf')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (66, N'Tomi')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (67, N'Trix Stop')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (68, N'Ultra')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (69, N'Vanish')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (70, N'Vape')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (71, N'Vileda')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (72, N'Vim')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (73, N'VIX')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (74, N'Well done')
INSERT INTO [dbo].[Brand] ([BrandID], [Brand_name]) VALUES (75, N'Yak')

SET IDENTITY_INSERT [dbo].[Brand] OFF
